---
title: Indivisible SF
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  uploads:
    title: Uploads
    output: true
  media-items:
    title: media-items
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: representatives
  values:
    main-image: 
    phone-numbers: 
    website: 
- scope:
    path: ''
    type: media-items
  values:
    main-image: 
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
subtitle: We are thousands of San Franciscans resisting the Trump agenda through civic
  action.
email: sahadeva@sahadeva.com
description: Indivisible SF is a group of local residents inspired by the Indivisible
  Guide, which provides a practical framework for resisting the Trump agenda. By standing
  together, we can keep the pressure on our representatives to defend progressive
  values and fight for us in Washington.
baseurl: 
url: indivisiblesf.org
twitter_username: indivisiblesf
github_username: indivisiblesf
facebook_username: indivisiblesf
background-image: "/uploads/31773994174_c2e5706218_k.jpg"
mailchimp-form-id: 
member-count: '2,400'
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
