---
title: Indivisible City
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image:
    call-script-text:
    event-start-date:
    event-end-date:
    Location:
    RSVP-link:
    layout: post
 - scope:
    path: ''
    type: pages
   values:
    main-image:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    main-image:
    phone-numbers:
    website:
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image:
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code:
subtitle: We are thousands of local citizens resisting the Trump agenda through civic
  action.
email:
baseurl:
url:
twitter_username:
github_username:
facebook_username:
background-image: "/uploads/31773994174_c2e5706218_k.jpg"
mailchimp-form-embed:
member-count: '100'
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics:
