---
title: Indivisible SF
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image:
    call-script-text:
    event-start-date:
    event-end-date:
    Location:
    RSVP-link:
    layout: post
- scope:
    path: ''
    type: representatives
  values:
    main-image:
    phone-numbers:
    website:
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image:
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code:
subtitle: We are thousands of San Franciscans resisting the Trump agenda through civic
  action.
email: sahadeva@sahadeva.com
baseurl:
url: indivisibletemplate.com
twitter_username: sahadeva
github_username: sahadeva
facebook_username: sahadeva
background-image: "/uploads/31773994174_c2e5706218_k.jpg"
mailchimp-form-embed: "<!-- Begin MailChimp Signup Form -->\n<link href=\"//cdn-images.mailchimp.com/embedcode/classic-10_7.css\"
  rel=\"stylesheet\" type=\"text/css\">\n<style type=\"text/css\">\n\t#mc_embed_signup{background:#fff;
  clear:left; font:14px Helvetica,Arial,sans-serif; }\n\t/* Add your own MailChimp
  form style overrides in your site stylesheet or in this style block.\n\t   We recommend
  moving this block and the preceding CSS link to the HEAD of your HTML file. */\n</style>\n<div
  id=\"mc_embed_signup\">\n<form action=\"//sahadeva.us15.list-manage.com/subscribe/post?u=4d9901e9229b1612550cf08c5&amp;id=911e179b1d\"
  method=\"post\" id=\"mc-embedded-subscribe-form\" name=\"mc-embedded-subscribe-form\"
  class=\"validate\" target=\"_blank\" novalidate>\n    <div id=\"mc_embed_signup_scroll\">\n\t\n<div
  class=\"indicates-required\"><span class=\"asterisk\">*</span> indicates required</div>\n<div
  class=\"mc-field-group\">\n\t<label for=\"mce-EMAIL\">Email Address  <span class=\"asterisk\">*</span>\n</label>\n\t<input
  type=\"email\" value=\"\" name=\"EMAIL\" class=\"required email\" id=\"mce-EMAIL\">\n</div>\n<div
  class=\"mc-field-group size1of2\">\n\t<label for=\"mce-MMERGE1\">Zip Code </label>\n\t<input
  type=\"number\" name=\"MMERGE1\" class=\"\" value=\"\" id=\"mce-MMERGE1\">\n</div>\n\t<div
  id=\"mce-responses\" class=\"clear\">\n\t\t<div class=\"response\" id=\"mce-error-response\"
  style=\"display:none\"></div>\n\t\t<div class=\"response\" id=\"mce-success-response\"
  style=\"display:none\"></div>\n\t</div>    <!-- real people should not fill this
  in and expect good things - do not remove this or risk form bot signups-->\n    <div
  style=\"position: absolute; left: -5000px;\" aria-hidden=\"true\"><input type=\"text\"
  name=\"b_4d9901e9229b1612550cf08c5_911e179b1d\" tabindex=\"-1\" value=\"\"></div>\n
  \   <div class=\"clear\"><input type=\"submit\" value=\"Subscribe\" name=\"subscribe\"
  id=\"mc-embedded-subscribe\" class=\"button\"></div>\n    </div>\n</form>\n</div>\n<script
  type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script
  type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes
  = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='MMERGE1';ftypes[1]='number';}(jQuery));var
  $mcj = jQuery.noConflict(true);</script>\n<!--End mc_embed_signup-->"
member-count: '2,400'
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 3
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: "<script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-92963695-1', 'auto'); ga('send', 'pageview'); </script>"
